### PR TITLE
Add documentation on accepting Bitcoin oriented towards small business owners

### PR DESCRIPTION
**Pull request by ln2max**
Add some intro text and lay out the general outline. Still needs references to specific apps, service providers, etc.

### CODE REVIEW

**Comment by nolim1t** [comment]
You might also want to take a look at [this repo](https://gitlab.com/nolim1t/bitcoin-merchant-starter-kit) (or [this one](https://github.com/nolim1t/bitcoin-merchant-starter-kit) ) too.

I've got a guide (deployed as a github page) too

**Comment by nolim1t** [comment]
Though I need to update the wallets accepted LOL

**Comment by nolim1t** [comment]
You can find the page it deploys to [here](https://nolim1t.gitlab.io/bitcoin-merchant-starter-kit/)

**Comment by nolim1t** [comment]
looks good.. should update the links to what I suggested

**Comment by ln2max** [comment]
All the basics have been covered, I think. @lncm/lncm any comments / additions?

**Comment by nolim1t** [comment]
Take a look at some of my changes. For such a long document I suggest having link anchors too

**Comment by ln2max** [comment]
I'm not seeing any changes from you? what should I be looking at?

**Comment by ln2max** [comment]
thanks for the fixes @hitchcott going to merge it all now since it sounds like it's good

**Pull request merged**
